package edu.temple.cla.papolicy.transcriptdata;
// Generated Sep 23, 2010 3:30:16 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * CommitteeAliases generated by hbm2java
 */
public class CommitteeAliases  implements java.io.Serializable {


     private short id;
     private Short ctyCode;
     private String alternateName;
     private Short startYear;
     private Short endYear;
     private Short chamber;
     private String name;
     private Set<Transcript> transcripts = new HashSet<Transcript>();

    public CommitteeAliases() {
    }

	
    public CommitteeAliases(short id) {
        this.id = id;
    }
    public CommitteeAliases(short id, Short ctyCode, String alternateName, Short startYear, Short endYear, Short chamber, String name) {
       this.id = id;
       this.ctyCode = ctyCode;
       this.alternateName = alternateName;
       this.startYear = startYear;
       this.endYear = endYear;
       this.chamber = chamber;
       this.name = name;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Short getCtyCode() {
        return this.ctyCode;
    }
    
    public void setCtyCode(Short ctyCode) {
        this.ctyCode = ctyCode;
    }
    public String getAlternateName() {
        return this.alternateName;
    }
    
    public void setAlternateName(String alternateName) {
        this.alternateName = alternateName;
    }
    public Short getStartYear() {
        return this.startYear;
    }
    
    public void setStartYear(Short startYear) {
        this.startYear = startYear;
    }
    public Short getEndYear() {
        return this.endYear;
    }
    
    public void setEndYear(Short endYear) {
        this.endYear = endYear;
    }
    public Short getChamber() {
        return this.chamber;
    }
    
    public void setChamber(Short chamber) {
        this.chamber = chamber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set<Transcript> getTranscripts() {return transcripts;}

    public void setTranscripts(Set<Transcript> transcripts) {
        this.transcripts = transcripts;
    }



}


