package edu.temple.cla.papolicy.transcriptdata;
// Generated Sep 23, 2010 3:30:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transcript generated by hbm2java
 */
public class Transcript  implements java.io.Serializable {


     private String id;
     private Integer year;
     private Integer number;
     private Boolean budgetRelated;
     private Integer hearingYear;
     private Integer hearingMonth;
     private Integer hearingDay;
     private Date hearingDate;
     private String hearingLocation;
     private Integer pages;
     private Integer receivedYear;
     private Integer receivedMonth;
     private Integer receviedDay;
     private Date receivedDate;
     private String comments;
     private Date datePresentedToHouse;
     private String summary;
     private Boolean hasAudio;
     private String audioNotes;
     private Boolean hasVideo;
     private String videoNotes;
     private String transcriptURL;
     private Set<CommitteeAliases> committees;
     private Set<BillID> bills;
     private Set<Witness> witnesses;

    public Transcript() {
    }

    public Transcript(String id) {
        this.id = id;
    }
    public Transcript(String id, Integer year, Integer number, 
            Boolean budgetRelated, Integer hearingYear, Integer hearingMonth,
            Integer hearingDay, Date hearingDate, String hearingLocation, Integer pages,
            Integer receivedYear, Integer receivedMonth, Integer receivedDay,
            Date receivedDate, String comments, Date datePresentedToHouse, String summary,
            Boolean hasAudio, String audioNotes, Boolean hasVideo,
            String videoNotes, String transcriptUrl) {
       this.id = id;
       this.year = year;
       this.number = number;
       this.budgetRelated = budgetRelated;
       this.hearingYear = hearingYear;
       this.hearingMonth = hearingMonth;
       this.hearingDay = hearingDay;
       this.hearingDate = hearingDate;
       this.hearingLocation = hearingLocation;
       this.pages = pages;
       this.receivedYear = receivedYear;
       this.receivedMonth = receivedMonth;
       this.receviedDay = receivedDay;
       this.receivedDate = receivedDate;
       this.comments = comments;
       this.datePresentedToHouse = datePresentedToHouse;
       this.summary = summary;
       this.hasAudio = hasAudio;
       this.audioNotes = audioNotes;
       this.hasVideo = hasVideo;
       this.videoNotes = videoNotes;
       this.transcriptURL = transcriptUrl;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Boolean getBudgetRelated() {
        return this.budgetRelated;
    }
    
    public void setBudgetRelated(Boolean budgetRelated) {
        this.budgetRelated = budgetRelated;
    }
    public Integer getHearingYear() {
        return this.hearingYear;
    }
    
    public void setHearingYear(Integer hearingYear) {
        this.hearingYear = hearingYear;
    }
    public Integer getHearingMonth() {
        return this.hearingMonth;
    }
    
    public void setHearingMonth(Integer hearingMonth) {
        this.hearingMonth = hearingMonth;
    }
    public Integer getHearingDay() {
        return this.hearingDay;
    }
    
    public void setHearingDay(Integer hearingDay) {
        this.hearingDay = hearingDay;
    }
    
    public Date getHearingDate() {
        return this.hearingDate;
    }
    
    public void setHearingDate(Date hearingDate) {
        this.hearingDate = hearingDate;
    }
    
    public String getHearingLocation() {
        return this.hearingLocation;
    }
    
    public void setHearingLocation(String hearingLocation) {
        this.hearingLocation = hearingLocation;
    }
    public Integer getPages() {
        return this.pages;
    }
    
    public void setPages(Integer pages) {
        this.pages = pages;
    }
    public Integer getReceivedYear() {
        return this.receivedYear;
    }
    
    public void setReceivedYear(Integer receivedYear) {
        this.receivedYear = receivedYear;
    }
    public Integer getReceivedMonth() {
        return this.receivedMonth;
    }
    
    public void setReceivedMonth(Integer receivedMonth) {
        this.receivedMonth = receivedMonth;
    }
    public Integer getReceviedDay() {
        return this.receviedDay;
    }
    
    public void setReceviedDay(Integer receivedDay) {
        this.receviedDay = receivedDay;
    }
    
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getDatePresentedToHouse() {
        return this.datePresentedToHouse;
    }
    
    public void setDatePresentedToHouse(Date datePresentedToHouse) {
        this.datePresentedToHouse = datePresentedToHouse;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public Boolean getHasAudio() {
        return this.hasAudio;
    }
    
    public void setHasAudio(Boolean hasAudio) {
        this.hasAudio = hasAudio;
    }
    public String getAudioNotes() {
        return this.audioNotes;
    }
    
    public void setAudioNotes(String audioNotes) {
        this.audioNotes = audioNotes;
    }
    public Boolean getHasVideo() {
        return this.hasVideo;
    }
    
    public void setHasVideo(Boolean hasVideo) {
        this.hasVideo = hasVideo;
    }
    public String getVideoNotes() {
        return this.videoNotes;
    }
    
    public void setVideoNotes(String videoNotes) {
        this.videoNotes = videoNotes;
    }
    public String getTranscriptURL() {
        return this.transcriptURL;
    }
    
    public void setTranscriptURL(String transcriptUrl) {
        this.transcriptURL = transcriptUrl;
    }

    /**
     * @return the witnesses
     */
    public Set<Witness> getWitnesses() {
        return witnesses;
    }

    /**
     * @param witnesses the witnesses to set
     */
    public void setWitnesses(Set<Witness> witnesses) {
        this.witnesses = witnesses;
    }

    public Set<CommitteeAliases> getCommittees() {return committees;}

    public void setCommittees(Set<CommitteeAliases> committees) {
        this.committees = committees;
    }

    public Set<BillID> getBills() {return bills;}
    public void setBills(Set<BillID> bills) {
        this.bills = bills;
    }
}


