package edu.temple.cla.papolicy.transcriptdata;
// Generated Sep 23, 2010 3:30:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Witness generated by hbm2java
 */
public class Witness  implements java.io.Serializable {


     private Integer id;
     private String salutation;
     private String firstName;
     private String middleName;
     private String suffix;
     private String lastName;
     private String title;
     private String testimonyURL;
     private Transcript transcript;

    public Witness() {
    }

    public Witness(String salutation, String firstName, String middleName,
            String suffix, String lastName, String title, String testimonyUrl) {
       this.salutation = salutation;
       this.firstName = firstName;
       this.middleName = middleName;
       this.suffix = suffix;
       this.lastName = lastName;
       this.title = title;
       this.testimonyURL = testimonyUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getSuffix() {
        return this.suffix;
    }
    
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTestimonyURL() {
        return this.testimonyURL;
    }
    
    public void setTestimonyURL(String testimonyUrl) {
        this.testimonyURL = testimonyUrl;
    }

    public Transcript getTranscript() {return transcript;}

    public void setTranscript(Transcript transcript) {
        this.transcript = transcript;
    }

}


